### ISSUE TITLE
Crash report GUI

### ISSUE THREAD

**Issue by doarlock** [Caltinor/Guild_and_Commerce#2]
[crash-2020-06-23_22.12.00-client.txt](https://github.com/Caltinor/Guild_and_Commerce/files/4829199/crash-2020-06-23_22.12.00-client.txt)

**Comment by Caltinor** [comment]
Thank you.  That wasn't caused by the sublet menu, but it does show me there is an IndexOutOfBounds issue caused by the Market Manager, which I should look into.  Thank You.

**Comment by Caltinor** [comment]
Issue appears to be from current recommended version.  Updating to most recent Beta version should resolve this issue.
