### ISSUE TITLE
Electroblob's Wizardry Compatibility 

### ISSUE THREAD

**Issue by skwirtus** [Caltinor/Guild_and_Commerce#8]
Electroblob's Wizardry v4.2.11
Guild & Commerce v1.2.7a
Minecraft v1.12.2

When using the telekinsis spell from Electroblob's Wizardry between 6 - 8 blocks it allows block interactions within protected land. This allows opening of chests (vanilla) and other interactions with other mods (Compact Machines 3, Refined Storage, etc.). Greater telekinsis will move blocks within protected land. As I explore Elecrtoblob's further I will update.

**Comment by Caltinor** [comment]
This is unfortunately unavoidable without some seriously hacky code. The implementation of which would severely negatively impact performance. As such, it is recommended that any spells which bypass protections in an undesirable way be disabled in Wizardy's config. 

The reason behind this has to do with Wizardy's lack of event posting. Without posting their spell behavior to the forge event bus, there is no way to intercept their changes to the world.
